Pod::Spec.new do |s|
  s.name = 'FoundationExtend'
  s.version = '0.1'
  s.license = 'MIT'
  s.summary = 'Foundation framework extend'
  s.homepage = 'https://github.com/zhujiaquan/FoundationExtend'
  s.author = { 'jiaquan.zhu' => 'jquan.zhu@gmail.com' }
  s.source = { :git => 'https://github.com/zhujiaquan/FoundationExtend.git', :tag => '0.1' }

  s.source_files = '*.{h,m}'
  s.compiler_flags = '-fno-objc-arc'
end
